#!/usr/bin/env python3
# guard_derived.py - protect DERIVED artifacts from hand-edits.
# Derived artifacts are a function of their upstream; they change ONLY by re-running their
# derive-* (or codegen) skill, which reconciles them. Hand-editing them breaks "derived = f(upstream)".
#   check (default): hash every derived file, compare to .claude/derived.lock; any mismatch = a hand-edit = exit 1.
#   --record [paths...]: (re)hash the given derived files (or all) into the lock. A derive skill runs this
#                        right after (re)writing its artifact, so a legit regeneration keeps file+lock in sync.
# Stdlib only. Run from the project root. Override in emergencies with `git commit --no-verify`.
import sys, os, hashlib, json, glob

# Directories owned by derive-* skills (regenerate-only) + the generated CLAUDE.md.
DERIVED_PREFIXES = [
    "spec/05-req-functional/",
    "spec/09-solution/",                 # arch, data, api, security, infra-ops, observability, test, impl
    "spec/10-delivery/conventions/",
    "spec/10-delivery/tasks/",
]
DERIVED_FILES_EXACT = ["CLAUDE.md"]   # generated by derive-conventions
LOCK = os.path.join(".claude", "derived.lock")

def _norm(p): return p.replace("\\", "/")
def is_derived(p):
    p = _norm(p)
    return p in DERIVED_FILES_EXACT or any(p.startswith(x) for x in DERIVED_PREFIXES)

def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(8192), b""): h.update(b)
    return h.hexdigest()

def load_lock():
    try: return json.load(open(LOCK))
    except Exception: return {}

def save_lock(d):
    os.makedirs(os.path.dirname(LOCK), exist_ok=True)
    json.dump(dict(sorted(d.items())), open(LOCK, "w"), indent=0)
    open(LOCK, "a").write("\n")

def all_derived():
    out = set(f for f in DERIVED_FILES_EXACT if os.path.isfile(f))
    for pre in DERIVED_PREFIXES:
        for f in glob.glob(pre + "**/*", recursive=True):
            if os.path.isfile(f) and not os.path.basename(f).startswith("."):
                out.add(_norm(f))
    return sorted(out)

def record(paths):
    lock = load_lock()
    targets = [_norm(p) for p in paths] if paths else all_derived()
    n = 0
    for p in targets:
        if is_derived(p) and os.path.isfile(p):
            lock[p] = sha(p); n += 1
    save_lock(lock)
    print("derived.lock updated for %d path(s)." % n)
    return 0

def check():
    lock = load_lock(); files = all_derived(); problems = []
    for p in files:
        if p not in lock:
            problems.append(("UNREGISTERED", p, "new derived file not produced via its skill (run --record after regenerating)"))
        elif lock[p] != sha(p):
            problems.append(("HAND-EDITED", p, "derived artifact changed without regeneration"))
    for p in lock:
        if not os.path.isfile(p):
            problems.append(("MISSING", p, "tracked derived file deleted"))
    if problems:
        print("FAIL: derived-artifact guard - derived files are regenerate-only:")
        for kind, p, msg in problems:
            print("  [%s] %s - %s" % (kind, p, msg))
        print("\nDerived artifacts are a function of their upstream. To change one, edit the UPSTREAM")
        print("(an authored/interview artifact) and RE-RUN its derive-* skill - it reconciles and updates")
        print("the lock. Never hand-edit a derived file. (Emergency override: git commit --no-verify.)")
        return 1
    print("OK: derived-artifact guard - %d derived file(s) match the lock." % len(files))
    return 0

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--record":
        sys.exit(record(sys.argv[2:]))
    sys.exit(check())
